title: Siti Nur Faiqah Zuraidy # your name (or website title) here
logo: "/images/pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Inspired to be a data analyst and a data scientist.  
  <br><br>
  This portfolio will show my journey in data analytics and data science. 
  <br><br>
  
  <a href="https://www.linkedin.com/in/sitinurfaiqahzuraidy/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
